///////////////////////////////////////////////////////////
//  IRequest.as
//  Macromedia ActionScript Implementation of the Interface IRequest
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 10:59:41
//  Original author: lifeng
///////////////////////////////////////////////////////////

package  org.lifeng.net
{
	/**
	 * <font color="#000000">所有通讯的对象接口。</font>
	 * @author lifeng
	 * @version 1.0
	 * @created 03-八月-2010 10:59:41
	 */
	public interface IRequest
	{
	}//end IRequest

}