///////////////////////////////////////////////////////////
//  ICommunication.as
//  Macromedia ActionScript Implementation of the Interface ICommunication
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 10:59:40
//  Original author: lifeng
///////////////////////////////////////////////////////////

package com.crystalcg.ncity.interfaces.communication
{
	/**
	 * <font color="#000000">所有通讯模块的通讯接口。</font>
	 * @author lifeng
	 * @version 1.0
	 * @updated 03-八月-2010 18:12:48
	 */
	public interface ICommunication
	{
		/**
		 * 
		 * @param request    发送请求对象。
		 * @param functionHandler    处理方法
		 */
		function send(request:IRequest, functionHandler:Function): int;
	}//end ICommunication

}