///////////////////////////////////////////////////////////
//  Icomponent.as
//  Macromedia ActionScript Implementation of the Interface Icomponent
//  Generated by Enterprise Architect
//  Created on:      13-八月-2010 14:36:20
//  Original author: lifeng
///////////////////////////////////////////////////////////

package com.crystalcg.ncity.interfaces.component
{
	import flash.display.BitmapData;

	/**
	 * 组件接口。
	 * @author lifeng
	 * @version 1.0
	 * @updated 25-八月-2010 15:16:19
	 */
	public interface Icomponent
	{
		/**
		 * 销毁方法
		 */
		function dispose(): void;

		/**
		 * 初始化。
		 */
		function initialize(): void;

		/**
		 * 
		 * @param value    路径对象
		 */
		function setPath(value:Object): void;

		/**
		 * 获取控件当前的影像。
		 */
		function getComponentImage(): BitmapData;
	}//end Icomponent

}