///////////////////////////////////////////////////////////
//  DataBaseManager.as
//  Macromedia ActionScript Implementation of the Class DataBaseManager
//  Generated by Enterprise Architect
//  Created on:      13-十二?2011 14:35:40
//  Original author: lifeng
///////////////////////////////////////////////////////////

package org.lifeng.db
{
	import flash.data.SQLConnection;
	import flash.data.SQLResult;
	import flash.data.SQLStatement;
	import flash.events.EventDispatcher;
	import flash.events.SQLErrorEvent;
	import flash.events.SQLEvent;
	import flash.filesystem.File;
	import flash.net.FileFilter;

	/**
	 * 数据库管理者。
	 * @author lifeng
	 * @version 1.0
	 * @updated 22-十二月-2011 14:10:19
	 */
	public class DataBaseManager extends EventDispatcher
	{
		public var condb:SQLConnection=new SQLConnection();
		private var sqlArray:Array=new Array();
		private var _lock:Boolean=false;
		public function DataBaseManager(){
			//trace("this is database manager aaaaaaaaaaaaaaaaaaa");
		}
		/**
		 * 打开数据库。
		 * 
		 * @param dbname
		 */
		public function openDB(dbpath:String):void
		{
			var file:File=new File(File.applicationDirectory.resolvePath(dbpath).nativePath);
			//var file:File=new File(dbpath);
			condb=new SQLConnection();
			condb.open(file);
			trace("打开数据库成功")
		}
		public function createDB(dbname:String):void{
			var file:File=new File(File.applicationDirectory.resolvePath(dbname).nativePath);
			if(!file.exists){
				
			}
			
		}
		public function execute(sqltext:String,pri:Number=10):void{
			sqlArray.push({sql:sqltext,priority:pri});
			next();
		}		
		public function executeNow(sqltext:String):Array
		{
			var smt:SQLStatement=new SQLStatement();
			smt.sqlConnection=condb;
			smt.text=sqltext;
			smt.execute();
			var result:SQLResult=smt.getResult();
			return result.data;
		}
		/**
		 * 关闭数据库。
		 * 
		 * @param dbname
		 */
		public function closeDB(dbname:String):void
		{
			condb.close();
			
		}
		private function next():void{
			if(!_lock){
				if(sqlArray.length>0){
					_lock=true;
					var obj:Object=sqlArray.shift();
					var sqltxt:String=obj.sql;
					var smt:SQLStatement=new SQLStatement();
					smt.addEventListener(SQLEvent.RESULT,resultHandler);
					smt.sqlConnection=condb;
					smt.text=sqltxt;//"select * from users";
					smt.execute();
				}
			}
		}
		private function resultHandler(e:SQLEvent):void{
			_lock=false;
			next();
		}

	}//end DataBaseManager

}