///////////////////////////////////////////////////////////
//  AbsComponent.as
//  Macromedia ActionScript Implementation of the Class AbsComponent
//  Generated by Enterprise Architect
//  Created on:      04-一月-2012 11:52:48
//  Original author: lifeng
///////////////////////////////////////////////////////////

package  com.crystalcg.ncity.mvc.view.compent
{
	import flash.display.Sprite;

	/**
	 * @author lifeng
	 * @version 1.0
	 * @created 04-一月-2012 11:52:48
	 */
	public class AbsComponent extends Sprite
	{
		public var TYPE:String="";
		public function AbsComponent(){

		}
		/**
		 * 销毁显示对象。
		 */
		public function dispose(): void
		{
		}
	}//end AbsComponent

}