///////////////////////////////////////////////////////////
//  IRole.as
//  Macromedia ActionScript Implementation of the Interface IRole
//  Generated by Enterprise Architect
//  Created on:      13-八月-2010 18:21:14
//  Original author: lifeng
///////////////////////////////////////////////////////////

package com.crystalcg.ncity.interfaces.role
{
	import flash.display.BitmapData;

	/**
	 * 角色抽象类。
	 * @author lifeng
	 * @version 1.0
	 * @updated 13-八月-2010 18:23:29
	 */
	public interface IRole
	{

		/**
		 * 
		 * @param value    皮肤图片。
		 */
		function setBitmapData(value:BitmapData): void;

		/**
		 * 站立。
		 */
		function stand(): void;

		/**
		 * 按照路径行走。
		 * 
		 * @param value    数组。
		 */
		function walkLine(value:Array): void;

		/**
		 * 
		 * @param _imagepath    图片路径。
		 */
		function initByPath(_imagepath:String): void;
	}//end IRole

}