///////////////////////////////////////////////////////////
//  CommunicationDataFormat.as
//  Macromedia ActionScript Implementation of the Class CommunicationDataFormat
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 14:55:10
//  Original author: lifeng
///////////////////////////////////////////////////////////

package com.crystalcg.ncity.communication
{
	import flash.net.URLLoaderDataFormat;

	/**
	 * 通信返回的格式类型。
	 * @author lifeng
	 * @version 1.0
	 * @updated 03-八月-2010 16:28:50
	 */
	public class CommunicationDataFormat
	{
		public static  const BINARY:String=URLLoaderDataFormat.BINARY;
		//public static  const DISPLAY:String="displayobject";
		public static const TEXT:String=URLLoaderDataFormat.TEXT;
		public static const IMAGE: String = "image";
		public static const SWF: String = "swf";


	}//end CommunicationDataFormat

}