///////////////////////////////////////////////////////////
//  SocketRequest.as
//  Macromedia ActionScript Implementation of the Class SocketRequest
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 18:03:43
//  Original author: lifeng
///////////////////////////////////////////////////////////

package  com.crystalcg.ncity.communication.socket
{
	import com.crystalcg.ncity.interfaces.communication.IRequest;

	/**
	 * @author lifeng
	 * @version 1.0
	 * @created 03-八月-2010 18:03:43
	 */
	dynamic public class SocketRequest extends Object implements IRequest
	{
	    /**
	     * 命令字段。
	     */
		public var command:String="";
		/**
		 * 构造函数。
		 */
		public function SocketRequest(){

		}
		/**
		 * 添加属性 和值。
		 * 
		 * @param _name
		 * @param _value
		 */
		public function addProperty(_name:String,_value:*):void{
			this[_name]=_value;
		}
		/**
		 * 设置通讯命令，用于与后台协作。
		 * 
		 * @param value
		 */
		public function setCommand(value:String):void{
			command=value;
		}
	}//end SocketRequest

}