///////////////////////////////////////////////////////////
//  SwfLoader.as
//  Macromedia ActionScript Implementation of the Class SwfLoader
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 16:32:23
//  Original author: lifeng
///////////////////////////////////////////////////////////

package com.crystalcg.ncity.communication.http.loader
{
	import flash.display.Loader;
	import flash.events.Event;
	import flash.net.URLRequest;

	/**
	 * 加载swf。
	 * @author lifeng
	 * @version 1.0
	 * @created 03-八月-2010 16:32:23
	 */
	public class SwfLoader extends Loader
	{
	    private var _function: Function;
		//public static native function abs(x:Number):Number;

		public function SwfLoader(req:URLRequest,_func:Function){
			super();
			this.contentLoaderInfo.addEventListener(Event.COMPLETE,completeHandler);
			this.load(req);
			_function=_func;
		}
		private function completeHandler(e:Event):void{
			if(_function is Function){
				_function.call(null,this.content,this.loaderInfo);
			}
			this.contentLoaderInfo.removeEventListener(Event.COMPLETE,completeHandler);
			_function=null;
			this.unloadAndStop();
			this.unload();
			//this.close();
		}
	}//end SwfLoader

}