///////////////////////////////////////////////////////////
//  BinaryLoader.as
//  Macromedia ActionScript Implementation of the Class BinaryLoader
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 15:18:49
//  Original author: lifeng
///////////////////////////////////////////////////////////

package  org.lifeng.net.http.loader
{
	import flash.events.Event;
	import flash.net.URLLoader;
	import flash.net.URLLoaderDataFormat;
	import flash.net.URLRequest;
	import flash.utils.ByteArray;

	/**
	 * @author lifeng
	 * @version 1.0
	 * @created 03-八月-2010 15:18:49
	 */
	public class BinaryLoader extends URLLoader
	{
	    private var _function: Function;
		
		public function BinaryLoader(req:URLRequest,func:Function){
			_function=func;
			dataFormat=URLLoaderDataFormat.BINARY;
			addEventListener(Event.COMPLETE,completeHandler);
			load(req);
		}
		private function completeHandler(e:Event):void{
			_function.call(null,e.target.data as ByteArray);
			_function=null;
			removeEventListener(Event.COMPLETE,completeHandler);
		}

	}//end BinaryLoader

}