///////////////////////////////////////////////////////////
//  DisplayLoader.as
//  Macromedia ActionScript Implementation of the Class DisplayLoader
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 15:18:57
//  Original author: lifeng
///////////////////////////////////////////////////////////

package org.lifeng.net.http.loader
{
	import flash.display.Loader;

	/**
	 * @author lifeng
	 * @version 1.0
	 * @created 03-八月-2010 15:18:57
	 */
	public class DisplayLoader extends Loader
	{
	    private var _function: Function;

		public function DisplayLoader(){

		}

	}//end DisplayLoader

}