///////////////////////////////////////////////////////////
//  ImageLoader.as
//  Macromedia ActionScript Implementation of the Class ImageLoader
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 16:32:34
//  Original author: lifeng
///////////////////////////////////////////////////////////

package  org.lifeng.net.http.loader
{
	import flash.display.Loader;
	import flash.display.LoaderInfo;
	import flash.events.Event;
	import flash.events.IOErrorEvent;
	import flash.net.URLRequest;

	/**
	 * 读取图片，支持格式 png、jpg、gif。
	 * @author lifeng
	 * @version 1.0
	 * @updated 03-八月-2010 16:58:35
	 */
	public class ImageLoader extends Loader
	{
	    private var _function: Function;

		/**
		 * 
		 * @param req    请求对象。
		 * @param _func    处理方法。
		 */
		public function ImageLoader(req:URLRequest,_func:Function){
			super();
			this.contentLoaderInfo.addEventListener(Event.COMPLETE,completeHandler);
			this.contentLoaderInfo.addEventListener(IOErrorEvent.IO_ERROR,ioerrorHandler);
			this.load(req);
			_function=_func;
		}
		private function completeHandler(e:Event):void{
			//_function.call(null,this);
			if(_function is Function){
				_function.call(null,this.content,this.loaderInfo);
			}
			
			_function=null;
			this.contentLoaderInfo.removeEventListener(Event.COMPLETE,completeHandler);
			this.unloadAndStop();
			this.unload();
		}
		private function ioerrorHandler(e:IOErrorEvent):void{
			var loaderinfo:LoaderInfo=e.target as LoaderInfo;
		}
	}//end ImageLoader

}