///////////////////////////////////////////////////////////
//  TextLoader.as
//  Macromedia ActionScript Implementation of the Class TextLoader
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 15:19:05
//  Original author: lifeng
///////////////////////////////////////////////////////////

package org.lifeng.net.http.loader
{
	
	import flash.events.Event;
	import flash.net.URLLoader;
	import flash.net.URLRequest;

	/**
	 * @author lifeng
	 * @version 1.0
	 * @created 03-八月-2010 15:19:05
	 */
	public class TextLoader extends URLLoader
	{
	    private var _function: Function;

		public function TextLoader(request:URLRequest,func:Function){
			init();
			_function=func;
			this.load(request);
		}
		public function init():void{
			this.addEventListener(Event.COMPLETE,completeHandler);
		}
		private function completeHandler(e:Event):void{
			_function.call(null,e.target.data);
			this.removeEventListener(Event.COMPLETE,completeHandler);
			_function=null;
		}

	}//end TextLoader

}