///////////////////////////////////////////////////////////
//  HappyWorldEvent.as
//  Macromedia ActionScript Implementation of the Class HappyWorldEvent
//  Generated by Enterprise Architect
//  Created on:      03-八月-2010 10:59:40
//  Original author: lifeng
///////////////////////////////////////////////////////////

package   org.lifeng.events
{
	import flash.events.Event;

	/**
	 * @author lifeng
	 * @version 1.0
	 * @created 03-八月-2010 10:59:40
	 */
	public class CustomEvent extends Event
	{
	    private var _body: Object;
	    private var _command: String;
	    static public const EVENT_NAME: String="Custom_Event";

		/**
		 * 
		 * @param _command    命令名。
		 * @param _body    所带参数对象。
		 */
		public function CustomEvent(_com:String, _b:Object=null)
		{
			super(EVENT_NAME,false,false);
			_command=_com;
			_body=_b;
		}

		/**
		 * 获取参数对象。
		 */
		public function get body(): Object
		{
			return _body;
		}

		/**
		 * 获取命令名。
		 */
		public function get command(): String
		{
			return _command;
		}

	}//end HappyWorldEvent

}